[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
name = "drsa"
version = "0.1"
authors = [{ name = "Diefesson" }]
dependencies = ["argparse ~= 1.4.0"]

[project.optional-dependencies]
dev = ["build", "pip-tools", "pytest"]
